services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./public:/usr/src/app/public
      - ./views:/usr/src/app/views
      - ./controllers:/usr/src/app/controllers
      - ./models:/usr/src/app/models
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      - NODE_ENV=development
      - DEBUG=true
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.0
    platform: linux/amd64
    command: 
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sd2-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 5s
      timeout: 10s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: