version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./static:/usr/src/app/static  # Changed from public to static
      - ./views:/usr/src/app/views
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -c "echo '=== Starting Application ===';
      echo 'Waiting for database...';
      until mysqladmin ping -h db -u $$MYSQL_USER -p$$MYSQL_PASSWORD --silent; do
        sleep 5;
        echo 'Still waiting for database...';
      done;
      echo 'Database ready!';
      node app.js"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      - NODE_ENV=development
      - DEBUG=true
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.0
    platform: linux/amd64
    command: 
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sd2-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "admin", "-ppassword"]
      interval: 5s
      timeout: 10s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: admin
      PMA_PASSWORD: password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: